import { Inter } from "next/font/google";
import "./globals.css";
import "tw-elements/dist/css/tw-elements.min.css";
import { ContextProvider } from "@/context";
import { Providers } from "./nextUIProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ContextProvider>
        <Providers>
          <body className={inter.className}>{children}</body>
        </Providers>
      </ContextProvider>
    </html>
  );
}
